### ISSUE TITLE
'YAML::BadFile' error while linking CXX executable

### ISSUE THREAD

**Issue by bxbalaban** [rendayigit/SpaceLoader#6]

**Comment by mrtkrkrt** [comment]
![image](https://user-images.githubusercontent.com/55550212/156840360-b1a9141f-1a13-473f-b5b1-38bb470b3e5b.png)
Biz bu problemi daha önce tartıştık. Problemin nedeni hazır kütüphane fonksiyonu ile Current Directory'i almaya çalıştığımızda hata veriyor. Fakat elle yazıldığında herhangi bir sıkıntı olmuyor.

**Comment by mrtkrkrt** [comment]
Fixed.
